print("Persona 1")
p1=set(input("Hola, ¿Cuales son tus comidas favoritas?: ").split(","))
print("Persona 2")
p2=set(input("Hola, ¿Cuales son tus comidas favoritas?: ").split(","))
print("COMIDAS SIMILARES ENTRE PERSONA 1 Y 2")
print(p1&p2)
print("COMIDAS FAVORITAS DE LA PERSONA 1")
print(p1)
print("COMIDAS FAVORITAS DE LA PERSONA 2")
print(p2)